-- AlterTable
ALTER TABLE "collections" ADD COLUMN     "custom_boolean1_name" BOOLEAN,
ADD COLUMN     "custom_boolean1_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_boolean2_name" BOOLEAN,
ADD COLUMN     "custom_boolean2_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_boolean3_name" BOOLEAN,
ADD COLUMN     "custom_boolean3_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_date1_name" TIMESTAMP(3),
ADD COLUMN     "custom_date1_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_date2_name" TIMESTAMP(3),
ADD COLUMN     "custom_date2_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_date3_name" TIMESTAMP(3),
ADD COLUMN     "custom_date3_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_int1_name" INTEGER,
ADD COLUMN     "custom_int1_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_int2_name" INTEGER,
ADD COLUMN     "custom_int2_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_int3_name" INTEGER,
ADD COLUMN     "custom_int3_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_string1_name" TEXT,
ADD COLUMN     "custom_string1_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_string2_name" TEXT,
ADD COLUMN     "custom_string2_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_string3_name" TEXT,
ADD COLUMN     "custom_string3_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_text1_name" TEXT,
ADD COLUMN     "custom_text1_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_text2_name" TEXT,
ADD COLUMN     "custom_text2_state" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_text3_name" TEXT,
ADD COLUMN     "custom_text3_state" BOOLEAN NOT NULL DEFAULT false;
